---
name: Bluetti to MQTT

version: 1.6.24
slug: "bluetti2mqtt"
description: "MQTT bridge between Bluetti and Home Assistant with updated nano2dev support"
url: "https://github.com/noobshoes/bluetti3mqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
usb: true
map:
  - "share:rw"
init: false
services:
  - "mqtt:need"

options:
  mqtt_username: ""
  mqtt_password: ""
  mqtt_host: ""
  mqtt_port: ""
  mode: mqtt
  ha_config: normal
  # IMPORTANT: Set this to your Bluetti device's MAC address. Only one Bluetooth connection is allowed at a time (disconnect the app!)
  bt_mac: 00:11:22:33:44:55
  poll_sec: 30
  scan: false
  debug: false
schema:
  mqtt_username: str?
  mqtt_password: password?
  mqtt_host: str?
  mqtt_port: str?
  mode: list(mqtt|discovery|logger)
  ha_config: list(normal|none|advanced)
  bt_mac: match(^([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2}( ([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2})*$)
  poll_sec: int
  scan: bool
  debug: bool
